stages:
- build
- deploy_prod
- deploy_dev

variables:
  DOCKER_HOST: "dock-one.mars.haw-hamburg.de:5555"
  DOCKER_REGISTRY: "artifactory.mars.haw-hamburg.de:5002"
  SERVIE_NAME: "webui-svc"
  SERVIE_NAME_DEV: "webui-svc_dev"

build:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/node:boron
  script:
    - npm -g install --quiet bower gulp
    - npm install --quiet
    - bower install
    - gulp
    - npm prune --production
  artifacts:
    paths:
      - node_modules/
      - dist/
      - server/


deploy_prod:
  stage: deploy_prod
  script:
  - echo "test"
  - ls -l
  dependencies:
    - build

deploy_dev:
  stage: deploy_dev
  script:
    - docker build -t $SERVIE_NAME_DEV:latest -f Dockerfile_dev .
    - docker tag $SERVIE_NAME_DEV:latest $DOCKER_REGISTRY/$SERVIE_NAME_DEV:$CI_BUILD_ID
    - docker tag $SERVIE_NAME_DEV:latest $DOCKER_REGISTRY/$SERVIE_NAME_DEV:latest
    - docker tag $SERVIE_NAME_DEV:latest $DOCKER_REGISTRY/$SERVIE_NAME_DEV:$CI_BUILD_REF
    - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PW $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME_DEV:$CI_BUILD_ID
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME_DEV:latest
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME_DEV:$CI_BUILD_REF
