stages:
  - build
  - clean
  - deploy

variables:
  GIT_STRATEGY: fetch
  DOCKER_HOST: "dock-one.mars.haw-hamburg.de:5555"
  DOCKER_REGISTRY: "artifactory.mars.haw-hamburg.de:5002"
  SERVICE_NAME: "webui-svc"
  SERVICE_NAME_DEV: "webui-svc_dev"

build_dependencies:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/node:boron
  script:
    - npm -g install --quiet bower gulp
    - npm prune --quiet # remove old packages
    - npm install --quiet
    - bower install --quiet
    - 'echo "{
          \"pipelineId\": \"$CI_PIPELINE_ID\",
          \"commitId\": \"$CI_BUILD_REF\"
      }" > src/version.json'
    - gulp  # build dist/
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/
      - dist/
  cache:
    paths:
      - /usr/local/lib/node_modules
      - node_modules/
      - bower_components/
      - dist/

clean_production:
  stage: clean
  image: artifactory.mars.haw-hamburg.de:5000/node:boron
  script:
    - npm prune --quiet --production # cleanup development packages
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/

deploy_production:
  stage: deploy
  script:
    - export DOCKER_HOST=$DOCKER_HOST
    - mv node_modules/ node_modules_prod/ # fix some strange bug, where the name causes an issue.
    - docker build -t $SERVICE_NAME:latest .
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:$CI_PIPELINE_ID
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:latest
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:$CI_BUILD_REF
    - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PW $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_PIPELINE_ID
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:latest
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_BUILD_REF

deploy_development:
  stage: deploy
  script:
    - export DOCKER_HOST=$DOCKER_HOST
    - rm -rf dist/ # remove production directory.
    - docker build -t $SERVICE_NAME_DEV:latest -f Dockerfile_dev .
    - docker tag $SERVICE_NAME_DEV:latest $DOCKER_REGISTRY/$SERVICE_NAME_DEV:$CI_PIPELINE_ID
    - docker tag $SERVICE_NAME_DEV:latest $DOCKER_REGISTRY/$SERVICE_NAME_DEV:latest
    - docker tag $SERVICE_NAME_DEV:latest $DOCKER_REGISTRY/$SERVICE_NAME_DEV:$CI_BUILD_REF
    - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PW $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME_DEV:$CI_PIPELINE_ID
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME_DEV:latest
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME_DEV:$CI_BUILD_REF
  dependencies:
    - build_dependencies
