stages:
- build
- deploy

variables:
  DOCKER_HOST: "dock-one.mars.haw-hamburg.de:5555"
  DOCKER_REGISTRY: "artifactory.mars.haw-hamburg.de:5002"
  SERVICE_NAME: "webui-svc"
  SERVICE_NAME_DEV: "webui-svc_dev"

build_prod:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/node:boron
  script:
    - npm -g install --quiet bower gulp
    - npm install --quiet
    - bower install
    - gulp
    - npm prune --production
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/
      - dist/
      - server/
  cache:
    paths:
      - node_modules/

deploy_prod:
  stage: deploy
  script:
    - export DOCKER_HOST=$DOCKER_HOST
    - docker build -t $SERVICE_NAME:latest -f Dockerfile_prod .
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:$CI_BUILD_ID
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:latest
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:$CI_BUILD_REF
    - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PW $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_BUILD_ID
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:latest
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_BUILD_REF
  dependencies:
    - build_prod

deploy_dev:
  stage: deploy
  script:
    - export DOCKER_HOST=$DOCKER_HOST
    - docker build -t $SERVICE_NAME_DEV:latest -f Dockerfile_dev .
    - docker tag $SERVICE_NAME_DEV:latest $DOCKER_REGISTRY/$SERVICE_NAME_DEV:$CI_BUILD_ID
    - docker tag $SERVICE_NAME_DEV:latest $DOCKER_REGISTRY/$SERVICE_NAME_DEV:latest
    - docker tag $SERVICE_NAME_DEV:latest $DOCKER_REGISTRY/$SERVICE_NAME_DEV:$CI_BUILD_REF
    - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PW $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME_DEV:$CI_BUILD_ID
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME_DEV:latest
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME_DEV:$CI_BUILD_REF
