FROM artifactory.mars.haw-hamburg.de:5000/node:argon-slim

# make node show only warnings
ENV NPM_CONFIG_LOGLEVEL warn

RUN apt-get update && apt-get install -y bzip2 git libfreetype6 libfontconfig python build-essential

# bower:   is the frontend tool for dependencies
# gulp:    builds the frontend, dev, production etc.
# phantomJS: is a test suite.
RUN npm install -g bower gulp phantomjs

# Creat development and production directory
RUN mkdir /app
RUN mkdir /prod

# Add Npm and bower files (for caching reasons)
ADD package.json /app
ADD .npmrc /app
ADD bower.json /app
ADD .bowerrc /app
ADD package.json /prod
ADD .npmrc /prod

# Install development Dependencies
WORKDIR /app
RUN npm install --only=dev
RUN bower install --allow-root --quiet

# Install production Dependencies
WORKDIR /prod
RUN npm install --production

# Add code to the container
ADD . /app
WORKDIR /app

# Build production (dist) directory
RUN gulp

# Add entrypoint
ADD entrypoint.sh /entrypoint/
RUN chmod +x /entrypoint/entrypoint.sh

# Convert DOS lineendings to UNIX
RUN sed -i $'s/\r$//' /entrypoint/entrypoint.sh

# Cleanup
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Expose ports
EXPOSE 8080 8081

# Run it
ENTRYPOINT ["sh", "/entrypoint/entrypoint.sh"]
