FROM artifactory.mars.haw-hamburg.de:5000/node:boron-alpine

WORKDIR /app

COPY node_modules_prod/ /app/node_modules
COPY dist/ /app/dist
COPY server/ /app/server

EXPOSE 8080

ENTRYPOINT ["node", "server/app.js"]
