FROM artifactory.mars.haw-hamburg.de:5000/node:boron-alpine

WORKDIR /app

# TODO: just use node_modules needed for production
ADD node_modules /app
ADD dist /app
ADD server /app

EXPOSE 8080

ENTRYPOINT ["node", "server/app.js"]
