FROM artifactory.mars.haw-hamburg.de:5000/node:argon-slim

# make node shut up
ENV NPM_CONFIG_LOGLEVEL silent

# bzip2:  is needed by PhantomJS
# git:    is needed by bower dependency
RUN apt-get update && apt-get install -y bzip2 git

# bower:   is the frontend tool for dependencies
# gulp:    builds the frontend, dev, production etc.
RUN npm install -g bower gulp

# Creat development and production directory
RUN mkdir /app
RUN mkdir /prod

# Add Npm and bower files (for caching reasons)
ADD package.json /app
ADD .npmrc /app
ADD bower.json /app
ADD .bowerrc /app
ADD package.json /prod
ADD .npmrc /prod

# Install development Dependencies
WORKDIR /app
RUN npm install --only=dev
RUN bower install --allow-root --silent

# Install production Dependencies
WORKDIR /prod
RUN npm install --production

# Add code to the container
ADD . /app
WORKDIR /app

# Build production (dist) directory
RUN gulp

# Add entrypoint
ADD entrypoint.sh /
RUN chmod +x /entrypoint.sh

# Convert DOS lineendings to UNIX
RUN sed -i $'s/\r$//' /entrypoint.sh

# Expose ports
EXPOSE 3000 3001

# Run it
ENTRYPOINT ["sh", "/entrypoint.sh"]
